### ISSUE TITLE
CacheWarmupController not compatible with zend-mvc-console

### ISSUE THREAD

**Issue by eichie** [reinfi/zf-dependency-injection#22]
Hi, 

for ZendFramework 3, the CacheWarmupController must extend 'Zend\Mvc\Console\Controller\AbstractConsoleController' instead  'Zend\Mvc\Controller\AbstractConsoleController'.

see 
https://docs.zendframework.com/zend-mvc-console/migration/v2-to-v3/#abstractconsolecontroller

best regards

**Comment by reinfi** [comment]
hi @eichie ,

release version 3.0.1 which is now fully compatible with zend framework 3.

best regards
Martin

**Comment by eichie** [comment]
Awesome, Thank you. :smiley:
