### ISSUE TITLE
PHP8 Attributes for Injection

### ISSUE THREAD

**Issue by gennadigennadigennadi** [reinfi/zf-dependency-injection#41]
With PHP8 around the corner :-). 

I already spent sometime working on an AttributeExtractor an added Inject as an Attribute, but there is still some work to do. Also I have not wrapped my head around caching, yet.

What do you think about implementing injection via Attributes? 
I would like to contribute and open an draft.

**Comment by reinfi** [comment]
yeah for sure! Good idea!
