### ISSUE TITLE
PHP 8 compatibility

### ISSUE THREAD

**Issue by AnnaDamm** [reinfi/zf-dependency-injection#44]
Hi,

currently, this library is not PHP8 compatible. Maybe just the composer.json has to be changed?

**Comment by reinfi** [comment]
Yeah I know there are deprecation issues. Will try to fix it this week.

**Comment by reinfi** [comment]
@AnnaDamm 
Released version 4.2.0 which is actually PHP8 compatible but composer.json is not changed to allow php8 due to laminas-cache package not ready for PHP8.

I will try to replace the library with something more independent and general like https://github.com/php-fig/simple-cache.
